import { DataRow } from "./data";

export const sample: DataRow[] = [
	{
		date: "1985-3-11",
		campaign: "Branded Broad",
		channel: "PPC",
		contributionGroup: "Media",
		cost: 28,
		impressions: 1560,
	},
	{
		date: "1985-3-11",
		campaign: "Competitors Broad",
		channel: "PPC",
		contributionGroup: "Media",
		cost: 4,
		impressions: 5657,
	},
	{
		date: "1985-3-11",
		campaign: "Generic Broad",
		channel: "PPC",
		contributionGroup: "Non-Media",
		cost: 53,
		impressions: 5449,
	},
	{
		date: "1985-3-11",
		campaign: "X_B | UK | Exact",
		channel: "PPC",
		contributionGroup: "Non-Media",
		cost: 22,
		impressions: 2159,
	},
	{
		date: "1985-3-11",
		campaign: "X_HT | UK | FLA | Exact",
		channel: "PPC",
		contributionGroup: "Non-Media",
		cost: 25,
		impressions: 5486,
	},
	{
		date: "1985-3-11",
		campaign: "X_LT | UK | Competitors | Exact",
		channel: "PPC",
		contributionGroup: "Media",
		cost: 14,
		impressions: 8738,
	},
	{
		date: "1985-3-12",
		campaign: "Branded Broad",
		channel: "PPC",
		contributionGroup: "Media",
		cost: 65,
		impressions: 3075,
	},
	{
		date: "1985-3-12",
		campaign: "Competitors Broad",
		channel: "PPC",
		contributionGroup: "Media",
		cost: 53,
		impressions: 7272,
	},
	{
		date: "1985-3-12",
		campaign: "Generic Broad",
		channel: "PPC",
		contributionGroup: "Media",
		cost: 5,
		impressions: 499,
	},
	{
		date: "1985-3-12",
		campaign: "X_B | UK | Exact",
		channel: "PPC",
		contributionGroup: "Media",
		cost: 18,
		impressions: 7430,
	},
	{
		date: "1985-3-12",
		campaign: "X_HT | UK | FLA | Exact",
		channel: "PPC",
		contributionGroup: "Media",
		cost: 67,
		impressions: 9725,
	},
	{
		date: "1985-3-23",
		campaign: "X_LT | UK | Competitors | Exact",
		channel: "PPC",
		contributionGroup: "Non-Media",
		cost: 68,
		impressions: 2106,
	},
];

